version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: desarrollo
      POSTGRES_PASSWORD: Test123
      POSTGRES_DB: servicescar
    ports:
      - "5433:5432"

  web:
    build: .
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://desarrollo:Test123@db:5432/servicescar
